// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOjAEdTaefBEYra9KT6RHfBiyJVXD6Y6A',
    appId: '1:713938603954:web:9407bd901a41bd8ee19eab',
    messagingSenderId: '713938603954',
    projectId: 'divyadhristi-ff265',
    authDomain: 'divyadhristi-ff265.firebaseapp.com',
    storageBucket: 'divyadhristi-ff265.appspot.com',
    measurementId: 'G-9VWGX609Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFGjwZ52LDRJoszkxjzDneQCHumveAaw',
    appId: '1:713938603954:android:1706e45f452827e7e19eab',
    messagingSenderId: '713938603954',
    projectId: 'divyadhristi-ff265',
    storageBucket: 'divyadhristi-ff265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBigpiwuNg2tdjetMV4DKcG0aA7FmVKF78',
    appId: '1:713938603954:ios:b1d9fb8830729b1fe19eab',
    messagingSenderId: '713938603954',
    projectId: 'divyadhristi-ff265',
    storageBucket: 'divyadhristi-ff265.appspot.com',
    iosClientId: '713938603954-d2v4pmb18j8f7411n9rcf8b5hu8vsjqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.andhadhunapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBigpiwuNg2tdjetMV4DKcG0aA7FmVKF78',
    appId: '1:713938603954:ios:b1d9fb8830729b1fe19eab',
    messagingSenderId: '713938603954',
    projectId: 'divyadhristi-ff265',
    storageBucket: 'divyadhristi-ff265.appspot.com',
    iosClientId: '713938603954-d2v4pmb18j8f7411n9rcf8b5hu8vsjqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.andhadhunapp',
  );
}
